// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sparkhireruntimeservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sparkhire_runtime "ice_sparkhire_runtime/kitex_gen/sparkhire_runtime"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, req *sparkhire_runtime.PingRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.PingResponse, err error)
	RegisterUser(ctx context.Context, req *sparkhire_runtime.RegisterUserRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.RegisterUserResponse, err error)
	UserMailLogin(ctx context.Context, req *sparkhire_runtime.UserMailLoginRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UserMailLoginResponse, err error)
	FetchCurrentUser(ctx context.Context, req *sparkhire_runtime.FetchCurrentUserRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.FetchCurrentUserResponse, err error)
	SwitchUserRole(ctx context.Context, req *sparkhire_runtime.SwitchUserRoleRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.SwitchUserRoleResponse, err error)
	AddCandidate(ctx context.Context, req *sparkhire_runtime.AddCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.AddCandidateResponse, err error)
	EditCandidate(ctx context.Context, req *sparkhire_runtime.EditCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCandidateResponse, err error)
	GetCurrentCandidate(ctx context.Context, req *sparkhire_runtime.GetCurrentCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentCandidateResponse, err error)
	QueryTag(ctx context.Context, req *sparkhire_runtime.QueryTagRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.QueryTagResponse, err error)
	AddTag(ctx context.Context, req *sparkhire_runtime.AddTagRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.AddTagResponse, err error)
	BindTags(ctx context.Context, req *sparkhire_runtime.BindTagsRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.BindTagsResponse, err error)
	UnbindTags(ctx context.Context, req *sparkhire_runtime.UnbindTagsRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UnbindTagsResponse, err error)
	CreateEducationExp(ctx context.Context, req *sparkhire_runtime.CreateEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateEducationExpResponse, err error)
	EditEducationExp(ctx context.Context, req *sparkhire_runtime.EditEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditEducationExpResponse, err error)
	DeleteEducationExp(ctx context.Context, req *sparkhire_runtime.DeleteEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.DeleteEducationExpResponse, err error)
	GetCurrentEducationExp(ctx context.Context, req *sparkhire_runtime.GetCurrentUserEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentUserEducationExpResponse, err error)
	CreateCareerExperience(ctx context.Context, req *sparkhire_runtime.CreateCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateCareerExperienceResponse, err error)
	EditCareerExperience(ctx context.Context, req *sparkhire_runtime.EditCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCareerExperienceResponse, err error)
	GetCurrentUserCareerExperience(ctx context.Context, req *sparkhire_runtime.GetCurrentUserCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentUserCareerExperienceResponse, err error)
	DeleteCareerExperience(ctx context.Context, req *sparkhire_runtime.DeleteCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.DeleteCareerExperienceResponse, err error)
	ListMajor(ctx context.Context, req *sparkhire_runtime.ListMajorRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListMajorResponse, err error)
	ListIndustry(ctx context.Context, req *sparkhire_runtime.ListIndustryRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListIndustryResponse, err error)
	ListSchool(ctx context.Context, req *sparkhire_runtime.ListSchoolRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListSchoolResponse, err error)
	ListGeo(ctx context.Context, req *sparkhire_runtime.ListGeoRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListGeoResponse, err error)
	CreateCompany(ctx context.Context, req *sparkhire_runtime.CreateCompanyRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateCompanyResponse, err error)
	EditCompany(ctx context.Context, req *sparkhire_runtime.EditCompanyRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCompanyResponse, err error)
	SendVerifyCode(ctx context.Context, req *sparkhire_runtime.SendVerifyCodeRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.SendVerifyCodeResponse, err error)
	UploadFile(ctx context.Context, req *sparkhire_runtime.UploadFileRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UploadFileResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSparkhireRuntimeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSparkhireRuntimeServiceClient struct {
	*kClient
}

func (p *kSparkhireRuntimeServiceClient) Ping(ctx context.Context, req *sparkhire_runtime.PingRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) RegisterUser(ctx context.Context, req *sparkhire_runtime.RegisterUserRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.RegisterUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterUser(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) UserMailLogin(ctx context.Context, req *sparkhire_runtime.UserMailLoginRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UserMailLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserMailLogin(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) FetchCurrentUser(ctx context.Context, req *sparkhire_runtime.FetchCurrentUserRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.FetchCurrentUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchCurrentUser(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) SwitchUserRole(ctx context.Context, req *sparkhire_runtime.SwitchUserRoleRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.SwitchUserRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SwitchUserRole(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) AddCandidate(ctx context.Context, req *sparkhire_runtime.AddCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.AddCandidateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCandidate(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) EditCandidate(ctx context.Context, req *sparkhire_runtime.EditCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCandidateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditCandidate(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) GetCurrentCandidate(ctx context.Context, req *sparkhire_runtime.GetCurrentCandidateRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentCandidateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentCandidate(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) QueryTag(ctx context.Context, req *sparkhire_runtime.QueryTagRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.QueryTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryTag(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) AddTag(ctx context.Context, req *sparkhire_runtime.AddTagRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.AddTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddTag(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) BindTags(ctx context.Context, req *sparkhire_runtime.BindTagsRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.BindTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindTags(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) UnbindTags(ctx context.Context, req *sparkhire_runtime.UnbindTagsRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UnbindTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindTags(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) CreateEducationExp(ctx context.Context, req *sparkhire_runtime.CreateEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateEducationExpResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateEducationExp(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) EditEducationExp(ctx context.Context, req *sparkhire_runtime.EditEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditEducationExpResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditEducationExp(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) DeleteEducationExp(ctx context.Context, req *sparkhire_runtime.DeleteEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.DeleteEducationExpResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteEducationExp(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) GetCurrentEducationExp(ctx context.Context, req *sparkhire_runtime.GetCurrentUserEducationExpRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentUserEducationExpResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentEducationExp(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) CreateCareerExperience(ctx context.Context, req *sparkhire_runtime.CreateCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateCareerExperienceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCareerExperience(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) EditCareerExperience(ctx context.Context, req *sparkhire_runtime.EditCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCareerExperienceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditCareerExperience(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) GetCurrentUserCareerExperience(ctx context.Context, req *sparkhire_runtime.GetCurrentUserCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.GetCurrentUserCareerExperienceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentUserCareerExperience(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) DeleteCareerExperience(ctx context.Context, req *sparkhire_runtime.DeleteCareerExperienceRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.DeleteCareerExperienceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCareerExperience(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) ListMajor(ctx context.Context, req *sparkhire_runtime.ListMajorRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListMajorResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMajor(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) ListIndustry(ctx context.Context, req *sparkhire_runtime.ListIndustryRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListIndustryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListIndustry(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) ListSchool(ctx context.Context, req *sparkhire_runtime.ListSchoolRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListSchoolResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSchool(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) ListGeo(ctx context.Context, req *sparkhire_runtime.ListGeoRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.ListGeoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGeo(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) CreateCompany(ctx context.Context, req *sparkhire_runtime.CreateCompanyRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.CreateCompanyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCompany(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) EditCompany(ctx context.Context, req *sparkhire_runtime.EditCompanyRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.EditCompanyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditCompany(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) SendVerifyCode(ctx context.Context, req *sparkhire_runtime.SendVerifyCodeRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.SendVerifyCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendVerifyCode(ctx, req)
}

func (p *kSparkhireRuntimeServiceClient) UploadFile(ctx context.Context, req *sparkhire_runtime.UploadFileRequest, callOptions ...callopt.Option) (r *sparkhire_runtime.UploadFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadFile(ctx, req)
}
