// Code generated by Kitex v0.15.2. DO NOT EDIT.
package sparkhireruntimeservice

import (
	server "github.com/cloudwego/kitex/server"
	sparkhire_runtime "ice_sparkhire_runtime/kitex_gen/sparkhire_runtime"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler sparkhire_runtime.SparkhireRuntimeService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler sparkhire_runtime.SparkhireRuntimeService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
