// Code generated by Kitex v0.15.2. DO NOT EDIT.

package sparkhireruntimeservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	sparkhire_runtime "ice_sparkhire_runtime/kitex_gen/sparkhire_runtime"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newSparkhireRuntimeServicePingArgs,
		newSparkhireRuntimeServicePingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RegisterUser": kitex.NewMethodInfo(
		registerUserHandler,
		newSparkhireRuntimeServiceRegisterUserArgs,
		newSparkhireRuntimeServiceRegisterUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UserMailLogin": kitex.NewMethodInfo(
		userMailLoginHandler,
		newSparkhireRuntimeServiceUserMailLoginArgs,
		newSparkhireRuntimeServiceUserMailLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FetchCurrentUser": kitex.NewMethodInfo(
		fetchCurrentUserHandler,
		newSparkhireRuntimeServiceFetchCurrentUserArgs,
		newSparkhireRuntimeServiceFetchCurrentUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SwitchUserRole": kitex.NewMethodInfo(
		switchUserRoleHandler,
		newSparkhireRuntimeServiceSwitchUserRoleArgs,
		newSparkhireRuntimeServiceSwitchUserRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentCandidate": kitex.NewMethodInfo(
		getCurrentCandidateHandler,
		newSparkhireRuntimeServiceGetCurrentCandidateArgs,
		newSparkhireRuntimeServiceGetCurrentCandidateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditCandidateContractInfo": kitex.NewMethodInfo(
		editCandidateContractInfoHandler,
		newSparkhireRuntimeServiceEditCandidateContractInfoArgs,
		newSparkhireRuntimeServiceEditCandidateContractInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditCandidateProfile": kitex.NewMethodInfo(
		editCandidateProfileHandler,
		newSparkhireRuntimeServiceEditCandidateProfileArgs,
		newSparkhireRuntimeServiceEditCandidateProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditCandidateBasicInfo": kitex.NewMethodInfo(
		editCandidateBasicInfoHandler,
		newSparkhireRuntimeServiceEditCandidateBasicInfoArgs,
		newSparkhireRuntimeServiceEditCandidateBasicInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryTag": kitex.NewMethodInfo(
		queryTagHandler,
		newSparkhireRuntimeServiceQueryTagArgs,
		newSparkhireRuntimeServiceQueryTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddTag": kitex.NewMethodInfo(
		addTagHandler,
		newSparkhireRuntimeServiceAddTagArgs,
		newSparkhireRuntimeServiceAddTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindTags": kitex.NewMethodInfo(
		bindTagsHandler,
		newSparkhireRuntimeServiceBindTagsArgs,
		newSparkhireRuntimeServiceBindTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbindTags": kitex.NewMethodInfo(
		unbindTagsHandler,
		newSparkhireRuntimeServiceUnbindTagsArgs,
		newSparkhireRuntimeServiceUnbindTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateEducationExp": kitex.NewMethodInfo(
		createEducationExpHandler,
		newSparkhireRuntimeServiceCreateEducationExpArgs,
		newSparkhireRuntimeServiceCreateEducationExpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditEducationExp": kitex.NewMethodInfo(
		editEducationExpHandler,
		newSparkhireRuntimeServiceEditEducationExpArgs,
		newSparkhireRuntimeServiceEditEducationExpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteEducationExp": kitex.NewMethodInfo(
		deleteEducationExpHandler,
		newSparkhireRuntimeServiceDeleteEducationExpArgs,
		newSparkhireRuntimeServiceDeleteEducationExpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentEducationExp": kitex.NewMethodInfo(
		getCurrentEducationExpHandler,
		newSparkhireRuntimeServiceGetCurrentEducationExpArgs,
		newSparkhireRuntimeServiceGetCurrentEducationExpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateWishCareer": kitex.NewMethodInfo(
		createWishCareerHandler,
		newSparkhireRuntimeServiceCreateWishCareerArgs,
		newSparkhireRuntimeServiceCreateWishCareerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditWishCareer": kitex.NewMethodInfo(
		editWishCareerHandler,
		newSparkhireRuntimeServiceEditWishCareerArgs,
		newSparkhireRuntimeServiceEditWishCareerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateCareerExperience": kitex.NewMethodInfo(
		createCareerExperienceHandler,
		newSparkhireRuntimeServiceCreateCareerExperienceArgs,
		newSparkhireRuntimeServiceCreateCareerExperienceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditCareerExperience": kitex.NewMethodInfo(
		editCareerExperienceHandler,
		newSparkhireRuntimeServiceEditCareerExperienceArgs,
		newSparkhireRuntimeServiceEditCareerExperienceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentUserCareerExperience": kitex.NewMethodInfo(
		getCurrentUserCareerExperienceHandler,
		newSparkhireRuntimeServiceGetCurrentUserCareerExperienceArgs,
		newSparkhireRuntimeServiceGetCurrentUserCareerExperienceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCareerExperience": kitex.NewMethodInfo(
		deleteCareerExperienceHandler,
		newSparkhireRuntimeServiceDeleteCareerExperienceArgs,
		newSparkhireRuntimeServiceDeleteCareerExperienceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMajor": kitex.NewMethodInfo(
		listMajorHandler,
		newSparkhireRuntimeServiceListMajorArgs,
		newSparkhireRuntimeServiceListMajorResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListIndustry": kitex.NewMethodInfo(
		listIndustryHandler,
		newSparkhireRuntimeServiceListIndustryArgs,
		newSparkhireRuntimeServiceListIndustryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSchool": kitex.NewMethodInfo(
		listSchoolHandler,
		newSparkhireRuntimeServiceListSchoolArgs,
		newSparkhireRuntimeServiceListSchoolResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListGeo": kitex.NewMethodInfo(
		listGeoHandler,
		newSparkhireRuntimeServiceListGeoArgs,
		newSparkhireRuntimeServiceListGeoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCareer": kitex.NewMethodInfo(
		listCareerHandler,
		newSparkhireRuntimeServiceListCareerArgs,
		newSparkhireRuntimeServiceListCareerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateCompany": kitex.NewMethodInfo(
		createCompanyHandler,
		newSparkhireRuntimeServiceCreateCompanyArgs,
		newSparkhireRuntimeServiceCreateCompanyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditCompany": kitex.NewMethodInfo(
		editCompanyHandler,
		newSparkhireRuntimeServiceEditCompanyArgs,
		newSparkhireRuntimeServiceEditCompanyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCompany": kitex.NewMethodInfo(
		deleteCompanyHandler,
		newSparkhireRuntimeServiceDeleteCompanyArgs,
		newSparkhireRuntimeServiceDeleteCompanyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendVerifyCode": kitex.NewMethodInfo(
		sendVerifyCodeHandler,
		newSparkhireRuntimeServiceSendVerifyCodeArgs,
		newSparkhireRuntimeServiceSendVerifyCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadFile": kitex.NewMethodInfo(
		uploadFileHandler,
		newSparkhireRuntimeServiceUploadFileArgs,
		newSparkhireRuntimeServiceUploadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	sparkhireRuntimeServiceServiceInfo                = NewServiceInfo()
	sparkhireRuntimeServiceServiceInfoForClient       = NewServiceInfoForClient()
	sparkhireRuntimeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return sparkhireRuntimeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return sparkhireRuntimeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return sparkhireRuntimeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SparkhireRuntimeService"
	handlerType := (*sparkhire_runtime.SparkhireRuntimeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sparkhire_runtime",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServicePingArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServicePingResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).Ping(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServicePingArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServicePingArgs()
}

func newSparkhireRuntimeServicePingResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServicePingResult()
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceRegisterUserArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceRegisterUserResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).RegisterUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceRegisterUserArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceRegisterUserArgs()
}

func newSparkhireRuntimeServiceRegisterUserResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceRegisterUserResult()
}

func userMailLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceUserMailLoginArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceUserMailLoginResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).UserMailLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceUserMailLoginArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUserMailLoginArgs()
}

func newSparkhireRuntimeServiceUserMailLoginResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUserMailLoginResult()
}

func fetchCurrentUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceFetchCurrentUserArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceFetchCurrentUserResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).FetchCurrentUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceFetchCurrentUserArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceFetchCurrentUserArgs()
}

func newSparkhireRuntimeServiceFetchCurrentUserResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceFetchCurrentUserResult()
}

func switchUserRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceSwitchUserRoleArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceSwitchUserRoleResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).SwitchUserRole(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceSwitchUserRoleArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceSwitchUserRoleArgs()
}

func newSparkhireRuntimeServiceSwitchUserRoleResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceSwitchUserRoleResult()
}

func getCurrentCandidateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentCandidateArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentCandidateResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).GetCurrentCandidate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceGetCurrentCandidateArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentCandidateArgs()
}

func newSparkhireRuntimeServiceGetCurrentCandidateResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentCandidateResult()
}

func editCandidateContractInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateContractInfoArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateContractInfoResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditCandidateContractInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditCandidateContractInfoArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateContractInfoArgs()
}

func newSparkhireRuntimeServiceEditCandidateContractInfoResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateContractInfoResult()
}

func editCandidateProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateProfileArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateProfileResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditCandidateProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditCandidateProfileArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateProfileArgs()
}

func newSparkhireRuntimeServiceEditCandidateProfileResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateProfileResult()
}

func editCandidateBasicInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateBasicInfoArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditCandidateBasicInfoResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditCandidateBasicInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditCandidateBasicInfoArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateBasicInfoArgs()
}

func newSparkhireRuntimeServiceEditCandidateBasicInfoResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCandidateBasicInfoResult()
}

func queryTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceQueryTagArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceQueryTagResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).QueryTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceQueryTagArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceQueryTagArgs()
}

func newSparkhireRuntimeServiceQueryTagResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceQueryTagResult()
}

func addTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceAddTagArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceAddTagResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).AddTag(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceAddTagArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceAddTagArgs()
}

func newSparkhireRuntimeServiceAddTagResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceAddTagResult()
}

func bindTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceBindTagsArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceBindTagsResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).BindTags(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceBindTagsArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceBindTagsArgs()
}

func newSparkhireRuntimeServiceBindTagsResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceBindTagsResult()
}

func unbindTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceUnbindTagsArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceUnbindTagsResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).UnbindTags(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceUnbindTagsArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUnbindTagsArgs()
}

func newSparkhireRuntimeServiceUnbindTagsResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUnbindTagsResult()
}

func createEducationExpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceCreateEducationExpArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceCreateEducationExpResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).CreateEducationExp(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceCreateEducationExpArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateEducationExpArgs()
}

func newSparkhireRuntimeServiceCreateEducationExpResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateEducationExpResult()
}

func editEducationExpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditEducationExpArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditEducationExpResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditEducationExp(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditEducationExpArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditEducationExpArgs()
}

func newSparkhireRuntimeServiceEditEducationExpResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditEducationExpResult()
}

func deleteEducationExpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteEducationExpArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteEducationExpResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).DeleteEducationExp(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceDeleteEducationExpArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteEducationExpArgs()
}

func newSparkhireRuntimeServiceDeleteEducationExpResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteEducationExpResult()
}

func getCurrentEducationExpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentEducationExpArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentEducationExpResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).GetCurrentEducationExp(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceGetCurrentEducationExpArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentEducationExpArgs()
}

func newSparkhireRuntimeServiceGetCurrentEducationExpResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentEducationExpResult()
}

func createWishCareerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceCreateWishCareerArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceCreateWishCareerResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).CreateWishCareer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceCreateWishCareerArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateWishCareerArgs()
}

func newSparkhireRuntimeServiceCreateWishCareerResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateWishCareerResult()
}

func editWishCareerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditWishCareerArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditWishCareerResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditWishCareer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditWishCareerArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditWishCareerArgs()
}

func newSparkhireRuntimeServiceEditWishCareerResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditWishCareerResult()
}

func createCareerExperienceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceCreateCareerExperienceArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceCreateCareerExperienceResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).CreateCareerExperience(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceCreateCareerExperienceArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateCareerExperienceArgs()
}

func newSparkhireRuntimeServiceCreateCareerExperienceResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateCareerExperienceResult()
}

func editCareerExperienceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditCareerExperienceArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditCareerExperienceResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditCareerExperience(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditCareerExperienceArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCareerExperienceArgs()
}

func newSparkhireRuntimeServiceEditCareerExperienceResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCareerExperienceResult()
}

func getCurrentUserCareerExperienceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentUserCareerExperienceArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceGetCurrentUserCareerExperienceResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).GetCurrentUserCareerExperience(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceGetCurrentUserCareerExperienceArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentUserCareerExperienceArgs()
}

func newSparkhireRuntimeServiceGetCurrentUserCareerExperienceResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceGetCurrentUserCareerExperienceResult()
}

func deleteCareerExperienceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteCareerExperienceArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteCareerExperienceResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).DeleteCareerExperience(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceDeleteCareerExperienceArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteCareerExperienceArgs()
}

func newSparkhireRuntimeServiceDeleteCareerExperienceResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteCareerExperienceResult()
}

func listMajorHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceListMajorArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceListMajorResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).ListMajor(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceListMajorArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListMajorArgs()
}

func newSparkhireRuntimeServiceListMajorResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListMajorResult()
}

func listIndustryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceListIndustryArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceListIndustryResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).ListIndustry(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceListIndustryArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListIndustryArgs()
}

func newSparkhireRuntimeServiceListIndustryResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListIndustryResult()
}

func listSchoolHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceListSchoolArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceListSchoolResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).ListSchool(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceListSchoolArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListSchoolArgs()
}

func newSparkhireRuntimeServiceListSchoolResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListSchoolResult()
}

func listGeoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceListGeoArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceListGeoResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).ListGeo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceListGeoArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListGeoArgs()
}

func newSparkhireRuntimeServiceListGeoResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListGeoResult()
}

func listCareerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceListCareerArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceListCareerResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).ListCareer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceListCareerArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListCareerArgs()
}

func newSparkhireRuntimeServiceListCareerResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceListCareerResult()
}

func createCompanyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceCreateCompanyArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceCreateCompanyResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).CreateCompany(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceCreateCompanyArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateCompanyArgs()
}

func newSparkhireRuntimeServiceCreateCompanyResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceCreateCompanyResult()
}

func editCompanyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceEditCompanyArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceEditCompanyResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).EditCompany(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceEditCompanyArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCompanyArgs()
}

func newSparkhireRuntimeServiceEditCompanyResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceEditCompanyResult()
}

func deleteCompanyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteCompanyArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceDeleteCompanyResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).DeleteCompany(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceDeleteCompanyArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteCompanyArgs()
}

func newSparkhireRuntimeServiceDeleteCompanyResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceDeleteCompanyResult()
}

func sendVerifyCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceSendVerifyCodeArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceSendVerifyCodeResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).SendVerifyCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceSendVerifyCodeArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceSendVerifyCodeArgs()
}

func newSparkhireRuntimeServiceSendVerifyCodeResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceSendVerifyCodeResult()
}

func uploadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sparkhire_runtime.SparkhireRuntimeServiceUploadFileArgs)
	realResult := result.(*sparkhire_runtime.SparkhireRuntimeServiceUploadFileResult)
	success, err := handler.(sparkhire_runtime.SparkhireRuntimeService).UploadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSparkhireRuntimeServiceUploadFileArgs() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUploadFileArgs()
}

func newSparkhireRuntimeServiceUploadFileResult() interface{} {
	return sparkhire_runtime.NewSparkhireRuntimeServiceUploadFileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ping(ctx context.Context, req *sparkhire_runtime.PingRequest) (r *sparkhire_runtime.PingResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServicePingArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServicePingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RegisterUser(ctx context.Context, req *sparkhire_runtime.RegisterUserRequest) (r *sparkhire_runtime.RegisterUserResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceRegisterUserArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceRegisterUserResult
	if err = p.c.Call(ctx, "RegisterUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserMailLogin(ctx context.Context, req *sparkhire_runtime.UserMailLoginRequest) (r *sparkhire_runtime.UserMailLoginResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceUserMailLoginArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceUserMailLoginResult
	if err = p.c.Call(ctx, "UserMailLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchCurrentUser(ctx context.Context, req *sparkhire_runtime.FetchCurrentUserRequest) (r *sparkhire_runtime.FetchCurrentUserResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceFetchCurrentUserArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceFetchCurrentUserResult
	if err = p.c.Call(ctx, "FetchCurrentUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SwitchUserRole(ctx context.Context, req *sparkhire_runtime.SwitchUserRoleRequest) (r *sparkhire_runtime.SwitchUserRoleResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceSwitchUserRoleArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceSwitchUserRoleResult
	if err = p.c.Call(ctx, "SwitchUserRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentCandidate(ctx context.Context, req *sparkhire_runtime.GetCurrentCandidateRequest) (r *sparkhire_runtime.GetCurrentCandidateResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceGetCurrentCandidateArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceGetCurrentCandidateResult
	if err = p.c.Call(ctx, "GetCurrentCandidate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditCandidateContractInfo(ctx context.Context, req *sparkhire_runtime.EditCandidateContractInfoRequest) (r *sparkhire_runtime.EditCandidateContractInfoResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditCandidateContractInfoArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditCandidateContractInfoResult
	if err = p.c.Call(ctx, "EditCandidateContractInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditCandidateProfile(ctx context.Context, req *sparkhire_runtime.EditCandidateProfileRequest) (r *sparkhire_runtime.EditCandidateProfileResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditCandidateProfileArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditCandidateProfileResult
	if err = p.c.Call(ctx, "EditCandidateProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditCandidateBasicInfo(ctx context.Context, req *sparkhire_runtime.EditCandidateBasicInfoRequest) (r *sparkhire_runtime.EditCandidateBasicInfoResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditCandidateBasicInfoArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditCandidateBasicInfoResult
	if err = p.c.Call(ctx, "EditCandidateBasicInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryTag(ctx context.Context, req *sparkhire_runtime.QueryTagRequest) (r *sparkhire_runtime.QueryTagResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceQueryTagArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceQueryTagResult
	if err = p.c.Call(ctx, "QueryTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddTag(ctx context.Context, req *sparkhire_runtime.AddTagRequest) (r *sparkhire_runtime.AddTagResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceAddTagArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceAddTagResult
	if err = p.c.Call(ctx, "AddTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindTags(ctx context.Context, req *sparkhire_runtime.BindTagsRequest) (r *sparkhire_runtime.BindTagsResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceBindTagsArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceBindTagsResult
	if err = p.c.Call(ctx, "BindTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindTags(ctx context.Context, req *sparkhire_runtime.UnbindTagsRequest) (r *sparkhire_runtime.UnbindTagsResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceUnbindTagsArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceUnbindTagsResult
	if err = p.c.Call(ctx, "UnbindTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateEducationExp(ctx context.Context, req *sparkhire_runtime.CreateEducationExpRequest) (r *sparkhire_runtime.CreateEducationExpResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceCreateEducationExpArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceCreateEducationExpResult
	if err = p.c.Call(ctx, "CreateEducationExp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditEducationExp(ctx context.Context, req *sparkhire_runtime.EditEducationExpRequest) (r *sparkhire_runtime.EditEducationExpResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditEducationExpArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditEducationExpResult
	if err = p.c.Call(ctx, "EditEducationExp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteEducationExp(ctx context.Context, req *sparkhire_runtime.DeleteEducationExpRequest) (r *sparkhire_runtime.DeleteEducationExpResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceDeleteEducationExpArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceDeleteEducationExpResult
	if err = p.c.Call(ctx, "DeleteEducationExp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentEducationExp(ctx context.Context, req *sparkhire_runtime.GetCurrentUserEducationExpRequest) (r *sparkhire_runtime.GetCurrentUserEducationExpResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceGetCurrentEducationExpArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceGetCurrentEducationExpResult
	if err = p.c.Call(ctx, "GetCurrentEducationExp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateWishCareer(ctx context.Context, req *sparkhire_runtime.CreateWishCareerRequest) (r *sparkhire_runtime.CreateWishCareerResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceCreateWishCareerArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceCreateWishCareerResult
	if err = p.c.Call(ctx, "CreateWishCareer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditWishCareer(ctx context.Context, req *sparkhire_runtime.EditWishCareerRequest) (r *sparkhire_runtime.EditWishCareerResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditWishCareerArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditWishCareerResult
	if err = p.c.Call(ctx, "EditWishCareer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateCareerExperience(ctx context.Context, req *sparkhire_runtime.CreateCareerExperienceRequest) (r *sparkhire_runtime.CreateCareerExperienceResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceCreateCareerExperienceArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceCreateCareerExperienceResult
	if err = p.c.Call(ctx, "CreateCareerExperience", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditCareerExperience(ctx context.Context, req *sparkhire_runtime.EditCareerExperienceRequest) (r *sparkhire_runtime.EditCareerExperienceResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditCareerExperienceArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditCareerExperienceResult
	if err = p.c.Call(ctx, "EditCareerExperience", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentUserCareerExperience(ctx context.Context, req *sparkhire_runtime.GetCurrentUserCareerExperienceRequest) (r *sparkhire_runtime.GetCurrentUserCareerExperienceResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceGetCurrentUserCareerExperienceArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceGetCurrentUserCareerExperienceResult
	if err = p.c.Call(ctx, "GetCurrentUserCareerExperience", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCareerExperience(ctx context.Context, req *sparkhire_runtime.DeleteCareerExperienceRequest) (r *sparkhire_runtime.DeleteCareerExperienceResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceDeleteCareerExperienceArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceDeleteCareerExperienceResult
	if err = p.c.Call(ctx, "DeleteCareerExperience", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMajor(ctx context.Context, req *sparkhire_runtime.ListMajorRequest) (r *sparkhire_runtime.ListMajorResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceListMajorArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceListMajorResult
	if err = p.c.Call(ctx, "ListMajor", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListIndustry(ctx context.Context, req *sparkhire_runtime.ListIndustryRequest) (r *sparkhire_runtime.ListIndustryResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceListIndustryArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceListIndustryResult
	if err = p.c.Call(ctx, "ListIndustry", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSchool(ctx context.Context, req *sparkhire_runtime.ListSchoolRequest) (r *sparkhire_runtime.ListSchoolResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceListSchoolArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceListSchoolResult
	if err = p.c.Call(ctx, "ListSchool", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGeo(ctx context.Context, req *sparkhire_runtime.ListGeoRequest) (r *sparkhire_runtime.ListGeoResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceListGeoArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceListGeoResult
	if err = p.c.Call(ctx, "ListGeo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCareer(ctx context.Context, req *sparkhire_runtime.ListCareerInfoRequest) (r *sparkhire_runtime.ListCareerInfoResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceListCareerArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceListCareerResult
	if err = p.c.Call(ctx, "ListCareer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateCompany(ctx context.Context, req *sparkhire_runtime.CreateCompanyRequest) (r *sparkhire_runtime.CreateCompanyResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceCreateCompanyArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceCreateCompanyResult
	if err = p.c.Call(ctx, "CreateCompany", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditCompany(ctx context.Context, req *sparkhire_runtime.EditCompanyRequest) (r *sparkhire_runtime.EditCompanyResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceEditCompanyArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceEditCompanyResult
	if err = p.c.Call(ctx, "EditCompany", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCompany(ctx context.Context, req *sparkhire_runtime.DeleteCompanyRequest) (r *sparkhire_runtime.DeleteCompanyResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceDeleteCompanyArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceDeleteCompanyResult
	if err = p.c.Call(ctx, "DeleteCompany", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendVerifyCode(ctx context.Context, req *sparkhire_runtime.SendVerifyCodeRequest) (r *sparkhire_runtime.SendVerifyCodeResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceSendVerifyCodeArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceSendVerifyCodeResult
	if err = p.c.Call(ctx, "SendVerifyCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadFile(ctx context.Context, req *sparkhire_runtime.UploadFileRequest) (r *sparkhire_runtime.UploadFileResponse, err error) {
	var _args sparkhire_runtime.SparkhireRuntimeServiceUploadFileArgs
	_args.Req = req
	var _result sparkhire_runtime.SparkhireRuntimeServiceUploadFileResult
	if err = p.c.Call(ctx, "UploadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
